image: docker-r3lab.uni.lu/imp/imp-withdb:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "$CI_PROJECT_DIR"
    LIBDIR: "/home/imp/lib"
    OUTPUTDIR: "$CI_PROJECT_DIR/testing/output"
    MG: "$CI_PROJECT_DIR/test/mg.r1.fq $CI_PROJECT_DIR/test/mg.r2.fq"
    MT: "$CI_PROJECT_DIR/test/mt.r1.fq $CI_PROJECT_DIR/test/mt.r2.fq"
    SAMPLE: "test"
    DBPATH: "/home/imp/databases"
    IMP_SUDO: "sudo"
    THREADS: "4"
    MEMTOTAL: "8"
    MEMCORE: "2"
    CONFIGFILE: "$CI_PROJECT_DIR/test/default.conf.json"

stages:
  - test_init
  - preprocessing

init:
  stage: test_init
  script:
    - snakemake -nps $CI_PROJECT_DIR/rules/ini/init

default:
    stage: preprocessing
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq
    artifacts:
      paths:
        - ${OUTPUTDIR}

mgmt-no-preprocessing:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_preprocessing.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq


mgmt-no-filtering:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_filtering.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq
