stages:
  - dag
  - init

databases:
    stage: init
    when: manual
    script:
        - ./test/scripts/init.sh


dag-mgmt:
  stage: dag
  script:
    - ./test/scripts/mgmt-dag.sh

dag-mg:
  stage: dag
  script:
    - ./test/scripts/mg-dag.sh

dag-mt:
  stage: dag
  script:
    - ./test/scripts/mt-dag.sh
