image: docker-r3lab.uni.lu/imp/imp:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "/home/imp/src"
    LIBDIR: "/home/imp/lib"
    OUTPUTDIR: "/output"
    MG: "/input/mg.r1.fq /input/mg.r2.fq"
    MT: "/input/mt.r1.fq /input/mt.r2.fq"
    SAMPLE: "test"
    DBPATH: "/databases"
    IMP_SUDO: "sudo"
    THREADS: 4
    MEMTOTAL: 8
    MEMCORE: 2

init:
  script:
      stage: test
      script:
          ls /home/imp/
          ls $CI_PROJECT_DIR
          snakemake -s /home/imp/code/rules/ini/init
