stages:
  - dag
  - preprocessing
  - init

databases:
    stage: init
    when: manual
    script:
        - ./test/scripts/init.sh


dag-mgmt:
  stage: dag
  script:
    - ./test/scripts/mgmt-dag.sh

dag-mg:
  stage: dag
  script:
    - ./test/scripts/mg-dag.sh

dag-mt:
  stage: dag
  script:
    - ./test/scripts/mt-dag.sh

p-mgmt:
    stage: preprocessing
    script:
        - ./test/scripts/mgmt-p.sh

p-mg:
    stage: preprocessing
    script:
        - ./test/scripts/mg-p.sh

p-mt:
    stage: preprocessing
    script:
        - ./test/scripts/mt-p.sh
