stages:
  - init
  - dag
  - preprocessing
  - assembly
  - analysis
  - binning
  - report

databases:
    stage: init
    when: manual
    script:
        - ./test/script/init.sh


dag-mgmt:
  stage: dag
  script:
    - ./test/script/mgmt-dag.sh
  artifacts:
    path:
        - ${CI_PROJECT_DIR}/output/*.pdf

dag-mg:
  stage: dag
  script:
    - ./test/script/mg-dag.sh
  artifacts:
    path:
        - ${CI_PROJECT_DIR}/output-mg/*.pdf

dag-mt:
  stage: dag
  script:
    - ./test/script/mt-dag.sh
  artifacts:
    path:
        - ${CI_PROJECT_DIR}/output-mt/*.pdf
