image: docker-r3lab.uni.lu/imp/imp:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "$CI_PROJECT_DIR"
    LIBDIR: "/home/imp/lib"
    INPUTDIR: "/input"
    OUTPUTDIR: "$CI_PROJECT_DIR/testing/output"
    MG: "/input/mg.r1.fq /input/mg.r2.fq"
    MT: "/input/mt.r1.fq /input/mt.r2.fq"
    SAMPLE: "test"
    DBPATH: "$CI_PROJECT_DIR/testing/databases"
    IMP_SUDO: "sudo"
    THREADS: "4"
    MEMTOTAL: "8"
    MEMCORE: "2"
    CONFIGFILE: "$CI_PROJECT_DIR/test/default.conf.json"

cache:
  key: "$CI_BUILD_NAME"
  untracked: true
  paths:
    - $DBPATH

stages:
  - inputs
  - init
  - preprocessing

databases:
  stage: inputs
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - ${DBPATH}
  artifacts:
    paths:
      - ${DBPATH}
  script:
    - apt-get update
    - apt-get -yq install curl
    - curl https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db.tgz | tar xzf -C $DBPATH --strip-components=1

raw_data:
  stage: inputs
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - ${INPUTDIR}
  artifacts:
    paths:
      - ${INPUTDIR}
  script:
    - apt-get update
    - apt-get -yq install curl
    - curl https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db.tgz | tar xzf -C $DBPATH --strip-components=1

init:
  stage: init
  script:
    - snakemake -nps $CI_PROJECT_DIR/rules/ini/init

default:
    stage: preprocessing
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq -np

mgmt-no-preprocessing:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_preprocessing.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq -np


mgmt-no-filtering:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_filtering.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq -np
