image: docker-r3lab.uni.lu/imp/imp-with:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "$CI_PROJECT_DIR"
    LIBDIR: "/home/imp/lib"
    OUTPUTDIR: "$CI_PROJECT_DIR/testing/output"
    MG: "$CI_PROJECT_DIR/test/MG.R1.small.fq $CI_PROJECT_DIR/test/MG.R2.small.fq"
    MT: "$CI_PROJECT_DIR/test/MT.R1.small.fq $CI_PROJECT_DIR/test/MT.R2.small.fq"
    SAMPLE: "test"
    DBPATH: "/home/imp/db"
    IMP_SUDO: "sudo"
    THREADS: "4"
    MEMTOTAL: "8"
    MEMCORE: "2"
    CONFIGFILE: "$CI_PROJECT_DIR/test/default.conf.json"

stages:
  - dag
  - preprocessing

init:
  stage: dag
  script:
    - snakemake -nps $CI_PROJECT_DIR/rules/ini/init

preprocessing:
  stage: dag
  script:
    - snakemake -np PREPROCESSING

assembly:
  stage: dag
  script:
    - snakemake -np ASSEMBLY

binning:
  stage: dag
  script:
    - snakemake -np BINNING

analysis:
  stage: dag
  script:
    - snakemake -np ANALYSIS

report:
  stage: dag
  script:
    - snakemake -np REPORT

default:
    stage: preprocessing
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq
    artifacts:
      paths:
        - ${OUTPUTDIR}

mgmt-no-preprocessing:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_preprocessing.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq


mgmt-no-filtering:
    stage: preprocessing
    variables:
        CONFIGFILE: "$CI_PROJECT_DIR/test/no_filtering.conf.json"
    script:
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq
