image: docker-r3lab.uni.lu/imp/imp:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "$CI_PROJECT_DIR"
    LIBDIR: "/home/imp/lib"
    OUTPUTDIR: "$CI_PROJECT_DIR/testing/output"
    MG: "/input/mg.r1.fq /input/mg.r2.fq"
    MT: "/input/mt.r1.fq /input/mt.r2.fq"
    SAMPLE: "test"
    DBPATH: "$CI_PROJECT_DIR/testing/databases"
    IMP_SUDO: "sudo"
    THREADS: "4"
    MEMTOTAL: "8"
    MEMCORE: "2"
    CONFIGFILE: "$CI_PROJECT_DIR/test/test.conf.json"


init:
  stage: test
  script:
    - snakemake -nps $CI_PROJECT_DIR/rules/ini/init

mgmt-preprocessing:
    stage: test
    script:
      - mkdir -p ~/databases/filtering
      - wget https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa.amb -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa.ann -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa.bwt -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa.pac -O ~/databases/filtering/.
      - https://webdav-r3lab.uni.lu/public/R3lab/IMP/test/db/filtering/chr1_human.fa.sa -O ~/databases/filtering/.
      - snakemake -s $CI_PROJECT_DIR/Snakefile Preprocessing/mg.r1.preprocessed.fq Preprocessing/mg.r2.preprocessed.fq Preprocessing/mg.se.preprocessed.fq Preprocessing/mt.r1.preprocessed.fq Preprocessing/mt.r2.preprocessed.fq Preprocessing/mt.se.preprocessed.fq -np
