image: docker-r3lab.uni.lu/imp/imp:1.4

variables:
    ROOT_DIR: "/home/imp/code"
    SRCDIR: "/home/imp/src"
    LIBDIR: "/home/imp/lib"
    OUTPUTDIR: "$CI_PROJECT_DIR/test/output"
    MG: "/input/mg.r1.fq /input/mg.r2.fq"
    MT: "/input/mt.r1.fq /input/mt.r2.fq"
    SAMPLE: "test"
    DBPATH: "$CI_PROJECT_DIR/test/databases"
    IMP_SUDO: "sudo"
    THREADS: "4"
    MEMTOTAL: "8"
    MEMCORE: "2"

init:
  stage: test
  script:
    - snakemake -s $CI_PROJECT_DIR/rules/ini/init
