stages:
  - dag
  - preprocessing
  - assembly
  - init

databases:
    stage: init
    when: manual
    script:
        - ./test/scripts/init.sh

dag-mgmt:
  stage: dag
  script:
      - ./IMP -m $CI_PROJECT_DIR/test/MG.R1.small.fq -m $CI_PROJECT_DIR/test/MG.R2.small.fq -t $CI_PROJECT_DIR/test/MT.R1.small.fq -t $CI_PROJECT_DIR/test/MT.R2.small.fq -c $CI_PROJECT_DIR/test/default.conf.json -d /mnt/data/db -o $CI_PROJECT_DIR/output --current "snakemake -n"

dag-mg:
  stage: dag
  script:
    - ./test/scripts/mg-dag.sh

dag-mt:
  stage: dag
  script:
    - ./test/scripts/mt-dag.sh

p-mgmt:
    stage: preprocessing
    script:
        - ./test/scripts/mgmt-p.sh

p-mgmt-nf:
    stage: preprocessing
    script:
        - ./test/scripts/mgmt-p-nf.sh

p-mgmt-np:
    stage: preprocessing
    script:
        - ./test/scripts/mgmt-p-np.sh

p-mg:
    stage: preprocessing
    script:
        - ./test/scripts/mg-p.sh

p-mg-nf:
    stage: preprocessing
    script:
        - ./test/scripts/mg-p-nf.sh

p-mg-np:
    stage: preprocessing
    script:
        - ./test/scripts/mg-p-np.sh

p-mt:
    stage: preprocessing
    script:
        - ./test/scripts/mt-p.sh

p-mt-nf:
    stage: preprocessing
    script:
        - ./test/scripts/mt-p-nf.sh

p-mt-np:
    stage: preprocessing
    script:
        - ./test/scripts/mt-p-np.sh

a-mgmt-idba:
    stage: assembly
    script:
        - ./test/scripts/mgmt-ass-idba.sh

a-mgmt-megahit:
    stage: assembly
    script:
        - ./test/scripts/mgmt-ass-megahit.sh
